export const schoolModelVocabulary = [
  "Accesso civico",
  "Albo",
  "Albo Sindacale",
  "Alternanza scuola lavoro",
  "Alternativa all'ora di religione",
  "Alunni",
  "Ammesso / Non ammesso",
  "Area riservata",
  "Attività extracurricolari",
  "Aula di musica",
  "Aula informatica",
  "Aula magna",
  "Aule",
  "Bacheca sindacale",
  "BES - Bisogni Educativi Speciali",
  "Biblioteca",
  "Biologia",
  "Calendario",
  "Certificati",
  "Chimica",
  "Chitarra",
  "Circolari",
  "Consigli di classe",
  "Consigli di istituto",
  "Contatti",
  "Corsi di musica",
  "Corsi serali",
  "Crediti formativi",
  "Didattica",
  "Diplomi",
  "Diritto ed economia",
  "Disegno",
  "Domande frequenti",
  "Educazione Tecnica",
  "eLearning",
  "Elettronica",
  "Erasmus",
  "Esame, esame di stato",
  "Filosofia",
  "Fisica",
  "Flauto",
  "Formazione docenti",
  "Galleria",
  "Gare sportive",
  "Genitori",
  "Geografia",
  "Giornale scolastico",
  "Gita scolastica",
  "Greco",
  "Indirizzi di studio",
  "Informatica",
  "Insegnanti",
  "Invalsi",
  "Iscrizioni",
  "Istituto",
  "Italiano",
  "Laboratori",
  "Latino",
  "Lettere",
  "Libri di testo",
  "Lingua francese",
  "Lingua inglese",
  "Lingua spagnola",
  "Lingua tedesca",
  "Marketing",
  "Matematica",
  "Mensa",
  "Modulistica",
  "Musica",
  "Notizie",
  "Offerta formativa",
  "Open Day",
  "Orario",
  "Organigramma",
  "Orientamento",
  "Pagamenti",
  "Palestra",
  "Personale ATA",
  "Pianoforte",
  "PON - Programma Operativo Nazionale",
  "Premi e concorsi",
  "Presidenza",
  "Privacy",
  "PTOF",
  "Ragioneria",
  "Rappresentante degli studenti",
  "Rappresentanti di classe dei genitori",
  "Rassegna stampa",
  "Recupero debiti",
  "Registro elettronico",
  "Regolamento d'istituto",
  "Religione cattolica",
  "RSU - Rappresentanza Sindacale Unitaria",
  "Scambi culturali",
  "Scienze",
  "Scienze motorie",
  "Scuola dell'infanzia",
  "Scuola primaria",
  "Scuola secondaria",
  "Sedi",
  "Segreteria",
  "Servizi",
  "Sicurezza",
  "Sindacati",
  "Storia",
  "Storia dell'arte",
  "Storia dell'istituto",
  "URP",
  "USR - Ufficio Scolastico Regionale",
  "UST - Ufficio Scolastico Territoriale",
  "Vicepresidenza",
  "Violino",
];
