export const cssClasses = [
  "row",
  "col",
  "card",
  "container",
  "variable-gutters",
  "section",
  "font-serif",
  "font-sans-serif",
  "font-monospace",
  "lead",
  "it-list",
  "link-list",
  "link-list-wrapper",
  "list-item",
  "text-primary",
  "text-secondary",
];
