export const secondLevelPageNames = [
  "Castello",
  "Fortezza",
  "Mura",
  "Roccaforte",
  "Torre",
  "Palazzo",
  "Trullo",
  "Villa",
  "Sito archeologico",
  "Parco archeologico",
  "Acquario",
  "Anfiteatro",
  "Archivio",
  "Auditorium",
  "Biblioteca",
  "Cinema",
  "Galleria",
  "Museo",
  "Osservatorio",
  "Pinacoteca",
  "Planetario",
  "Scuola",
  "Teatro",
  "Università/Facoltà",
  "Parco Archeologico",
  "Abbazia",
  "Chiesa",
  "Campanile",
  "Battistero",
  "Convento",
  "Duomo",
  "Edicola",
  "Eremo",
  "Mausoleo",
  "Monastero",
  "Santuario",
  "Sinagoga",
  "Tempio",
  "Sepolcro",
  "Basilica",
  "Cappella",
  "Catacomba",
  "Cattedrale",
  "Cimitero",
  "Archi",
  "Colonna",
  "Complesso monumentale",
  "Monumento",
  "Obelisco",
  "Belvedere",
  "Giardino",
  "Parco",
  "Viale",
  "Costa marittima",
  "Lago",
  "Corso d’acqua",
  "Montagna",
  "Ghiacciaio",
  "Riserva Naturale",
  "Foresta e bosco",
  "Vulcano",
  "Campo Sportivo",
  "Piscina",
  "Stadio",
  "Terme",
  "Casinò",
  "Circolo sportivo",
  "Piazza",
  "Mercati",
  "Farmacie",
  "Casa di riposo",
  "Centro di accoglienza",
  "Ospedale",
  "Centro di raccolta",
  "Acquedotto",
  "Aeroporto",
  "Porto",
  "Albergo",
  "Foresteria",
  "Rifugio",
  "Rifugio per animali",
];